research_task:
  description: >
    Conduct thorough research about post operative at-home patient monitoring
    for cardio-vascular patients. Use web search tools to find accurate, well-respected
    sources covering the following three topics: live monitoring of patient vitals,
    cardio post-operative recovery and complications to watch out for, and finally
    normal and abnormal ranges by age for heartbeats-per-minute, pulse-strength,
    spo2, temperature, blood pressure and ecg-rhythm.

    For each topic, find 5 high-quality articles from reputable medical sources
    such as PubMed, clinical guidelines, medical journals, or healthcare organizations.
    Extract the full content of each article for indexing.

    CRITICAL: Structure your output to match the MedicalKnowledgeDocument schema:
    - title: Article title
    - content: Full article content
    - source: Source name (e.g., "PubMed", "American Heart Association")
    - url: Article URL
    - topic_category: One of "patient_monitoring", "post_op_recovery", "vital_signs", "complications", "intervention_protocols"
    - keywords: List of relevant keywords
    - medical_terms: List of specific medical terms mentioned
    - relevance_score: Score from 0.0 to 1.0

  expected_output: >
    A comprehensive list of 15 high-quality medical articles (5 per topic) with the following structure for each article:
    - title: Article title
    - content: Full article content
    - source: Source name (e.g., "PubMed", "American Heart Association")
    - url: Article URL
    - topic_category: One of "patient_monitoring", "post_op_recovery", "vital_signs", "complications", "intervention_protocols"
    - keywords: List of relevant keywords
    - medical_terms: List of specific medical terms mentioned
    - relevance_score: Score from 0.0 to 1.0

    Format as a JSON list where each article is a properly structured object with all required fields.

  agent: researcher

indexing_task:
  description: >
    Review the medical articles provided by the researcher and index them into OpenSearch
    using the OpenSearchTool. The researcher will provide articles in the correct format.

    Your job is to:
    1. Use the OpenSearchTool to create the medical-knowledge-base index if it doesn't exist
    2. Index each article using the OpenSearchTool's index_document operation
    3. Verify that articles are properly indexed by searching for them
    4. Provide a summary of the indexing results

    The articles should be categorized by topic_category:
    - patient_monitoring: Articles about live monitoring of patient vitals
    - post_op_recovery: Articles about cardio post-operative recovery
    - vital_signs: Articles about normal/abnormal ranges for vital signs
    - complications: Articles about complications to watch out for
    - intervention_protocols: Articles about intervention protocols

  expected_output: >
    - Medical-knowledge-base index created in OpenSearch
    - All articles successfully indexed using OpenSearchTool
    - Verification that articles can be retrieved via search
    - Summary of indexing results including document counts
    - Any errors or warnings encountered during indexing

  agent: indexer
  context: [research_task]
